<?php
/**
 * @file
 * escom_resources_1.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function escom_resources_1_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'workshop notes',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '01090f58-a8ab-489a-9d75-a72217cebda6',
    'vocabulary_machine_name' => '_resource_type',
  );
  $terms[] = array(
    'name' => 'Conference 2017',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '08dba52c-707c-45eb-9490-c9e60b2422ee',
    'vocabulary_machine_name' => '_resource_type',
  );
  $terms[] = array(
    'name' => 'Presentation',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '157650ff-ef5b-44f0-bd4b-12d3dafb7716',
    'vocabulary_machine_name' => '_resource_type',
  );
  $terms[] = array(
    'name' => 'Software',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '1b187f31-408a-49d2-8067-5f32b3431d33',
    'vocabulary_machine_name' => '_resource_type',
  );
  $terms[] = array(
    'name' => 'Antwerp Conference',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '22ab4809-f182-45bc-8a0f-a931bc5e625b',
    'vocabulary_machine_name' => '_resource_type',
  );
  $terms[] = array(
    'name' => 'DATA & INFORMATION TOOLS',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '27c4a503-a6e6-4211-a38c-a788dbe119e0',
    'vocabulary_machine_name' => '_resource_type',
  );
  $terms[] = array(
    'name' => 'KNOWLEDGE & DECISION SUPPORT',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '493d08fc-c353-41e5-948f-79d3941c60b3',
    'vocabulary_machine_name' => '_resource_type',
  );
  $terms[] = array(
    'name' => 'Briefing paper',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '523d0ee9-2f68-4c79-b1e5-f4011197cbe7',
    'vocabulary_machine_name' => '_resource_type',
  );
  $terms[] = array(
    'name' => 'Workshop Summary Document',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '53f87e2b-b018-4ffd-b7c1-7cab4d8aac4c',
    'vocabulary_machine_name' => '_resource_type',
  );
  $terms[] = array(
    'name' => 'Woodland expansion workshop',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6665769d-edc6-40a6-833b-432cf29fc5dd',
    'vocabulary_machine_name' => '_resource_type',
  );
  $terms[] = array(
    'name' => 'Webinar',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6a93c184-7594-4994-8c40-c38b4a6f0dea',
    'vocabulary_machine_name' => '_resource_type',
  );
  $terms[] = array(
    'name' => 'Factsheet',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '800a51c7-ccc8-403b-ae5d-105de3197bbc',
    'vocabulary_machine_name' => '_resource_type',
  );
  $terms[] = array(
    'name' => 'Conference Paper',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '84b613d2-4c2c-45c4-9f2e-70a65726eb47',
    'vocabulary_machine_name' => '_resource_type',
  );
  $terms[] = array(
    'name' => 'ESP Antwerp Conference 2016',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8ec01c64-847b-4aa7-b2e5-7083d061d9f6',
    'vocabulary_machine_name' => '_resource_type',
  );
  $terms[] = array(
    'name' => 'conference programme',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '998c6926-0837-4fe7-b332-1f5ee0bfe982',
    'vocabulary_machine_name' => '_resource_type',
  );
  $terms[] = array(
    'name' => 'Journal Paper',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'a47b4161-ed15-4ef3-87df-946bc6b05774',
    'vocabulary_machine_name' => '_resource_type',
  );
  $terms[] = array(
    'name' => 'Teaching Material',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'b0eec390-d33f-44e8-83c5-1ead70950f81',
    'vocabulary_machine_name' => '_resource_type',
  );
  $terms[] = array(
    'name' => 'conference form',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b4ec5ce9-f199-4495-95ca-5af432ced48a',
    'vocabulary_machine_name' => '_resource_type',
  );
  $terms[] = array(
    'name' => 'UPTAKE & EVALUATION',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ba9a8b4c-d231-4195-9601-8c45b3977611',
    'vocabulary_machine_name' => '_resource_type',
  );
  $terms[] = array(
    'name' => 'POLICY INSTRUMENTS',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'cb07f842-c080-4f4d-bbd2-144158c79b0d',
    'vocabulary_machine_name' => '_resource_type',
  );
  $terms[] = array(
    'name' => 'ESCom governance',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'cfe8749a-626b-4201-888e-1fa56cf8dbbf',
    'vocabulary_machine_name' => '_resource_type',
  );
  $terms[] = array(
    'name' => 'Summary Report',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ec4944ad-4c6d-4d96-9a42-288093c09395',
    'vocabulary_machine_name' => '_resource_type',
  );
  $terms[] = array(
    'name' => 'Report',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'f9afbf01-447c-4538-a686-65443779529d',
    'vocabulary_machine_name' => '_resource_type',
  );
  return $terms;
}
